name: personal_finance
description: "A project for personal finance expenses and spending control."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  provider: ^6.1.2
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.1
  data_table_2: ^2.5.18
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/personal-finance-full-logo-transparent.png
    - assets/img/personal-finance-icon-transparent-logo.png
    - assets/img/personal-finance-high-resolution-logo-transparent.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
